services:
  - type: web
    name: peadesua-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: openai/gpt-oss-120b
      - key: GROQ_VISION_MODEL
        value: qwen/qwen3.6-27b
